INSERT INTO REVIEWS (RATING, COMMENT, PRODUCT_ID, CUSTOMER_ID)
VALUES (4, N'Nice design and functionality.', 3, 1),
       (5, N'Excellent customer service!', 4, 2),
       (2, N'Poor quality, wouldnt recommend.', 5, 3),
       (4, N'Fast shipping and good packaging.', 1, 4),
       (3, N'Mediocre performance, expected more.', 2, 5),
       (5, N'Love this product! Highly recommended.', 1, 1),
       (4, N'Great value for the price.', 3, 2),
       (2, N'Disappointed with the product quality.', 4, 3),
       (5, N'Amazing customer support.', 2, 4),
       (3, N'Average product, nothing special.', 5, 5),
       (4, N'Sturdy and durable construction.', 1, 1),
       (5, N'Best purchase I"ve made in a while.', 3, 2),
       (2, N'Product arrived damaged.', 4, 3),
       (4, N'Quick and easy setup process.', 2, 4),
       (3, N'Not as described, but still usable.', 5, 5),
       (4, N'Good value for the money.', 1, 1),
       (5, N'Impressive performance.', 3, 2),
       (2, N'Wish I had bought a different product.', 4, 3),
       (4, N'Helpful and knowledgeable customer service.', 2, 4),
       (3, N'Could be better, but serves its purpose.', 5, 5),
       (4, N'Excellent build quality.', 1, 1),
       (5, N'Highly satisfied with my purchase.', 3, 2),
       (2, N'Defective product, needs replacement.', 4, 3),
       (4, N'User-friendly interface.', 2, 4),
       (3, N'Average product, nothing exceptional.', 5, 5),
       (4, N'Great features and functionality.', 1, 1),
       (5, N'Outstanding customer support.', 3, 2),
       (2, N'Not worth the price tag.', 4, 3),
       (4, N'Fast and reliable shipping.', 2, 4),
       (3, N'Could use some improvements.', 5, 5),
       (4, N'Good product for everyday use.', 1, 1),
       (5, N'Impressed with the product quality.', 3, 2),
       (2, N'Product arrived late and damaged.', 4, 3),
       (4, N'Effortless setup and configuration.', 2, 4),
       (3, N'Overrated product, didn"t meet my expectations.', 5, 5),
       (4, N'Value for money purchase.', 1, 1),
       (5, N'Exceptional performance.', 3, 2),
       (2, N'Product lacks durability.', 4, 3),
       (4, N'Prompt and helpful customer service.', 2, 4),
       (3, N'Average product, nothing remarkable.', 5, 5),
       (4, N'Solid construction and design.', 1, 1),
       (5, N'Extremely satisfied with my purchase.', 3, 2),
       (2, N'Product arrived with missing parts.', 4, 3),
       (4, N'Seamless integration with other devices.', 2, 4),
       (3, N'Not the best product in its category.', 5, 5),
       (4, N'Reliable and efficient.', 1, 1),
       (5, N'Great value for the features.', 3, 2),
       (2, N'Unreliable performance, frequent crashes.', 4, 3),
       (4, N'Excellent customer assistance.', 2, 4),
       (3, N'Average product, nothing extraordinary.', 5, 5);
